<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Can.Core.BackgroundJobs.Hangfire\Can.Core.BackgroundJobs.Hangfire.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
