<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Can.Core.Reporting.AspNetCore\Can.Core.Reporting.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Can.Core.Reporting.EntityFrameworkCore\Can.Core.Reporting.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

</Project>
